### ISSUE TITLE
Could not load file or assembly 'Garyon,

### ISSUE THREAD

**Issue by ignatandrei** [RossLean/RossLean#21]
I want to add this to my list of Roslyn Source Code Generator

https://ignatandrei.github.io/RSCG_Examples/v2/docs/List-of-RSCG

but an error occurs :"Could not load file or assembly 'Garyon,"

Could you help me please?

For reproducing,please download 
[src.zip](https://github.com/RossLean/RossLean/files/15087935/src.zip)

**Comment by Rekkonnect** [comment]
Thanks for the repro, you are specifically talking about `RossLean.StringificationGenerator`. I'll have a fix made by tomorrow.

**Comment by Rekkonnect** [comment]
I lied, it took more time to get me to do the fix.

@ignatandrei please check again with version 1.0.1. The dependency issues should be resolved. I'll keep the issue open in case this was not fixed.

**Comment by ignatandrei** [comment]
Now it works!
Please see https://ignatandrei.github.io/RSCG_Examples/v2/docs/RossLean.StringificationGenerator 

Thanks!
Andrei
